set dotenv-load

start:
  PYVIEW_SECRET=`openssl rand -base64 16` cd src && poetry run uvicorn {{ cookiecutter.package_name }}.app:app --reload --port 7000

docker-build:
  docker build -t {{ cookiecutter.package_name }} .

docker-run:
  docker run -p 8000:8000 {{ cookiecutter.package_name }}

# Run all tests
test:
  poetry run pytest

type-check:
  poetry run pyright

# Adds a new view to the project
add-view name:
  poetry run pv create-view {{ "{{name}}" }}

